#pragma once

enum PageIndex
{
    OFF = 0,
    ON = 1,
    LOGIN_PAGE = 0,
    HOME_PAGE = 1,
    CREATE_PROFILE_PAGE = 2,
    OPTIONS_PAGE = 3,
    BOLUS_PAGE = 4,
    PROFILES_PAGE = 5,
    EDIT_PROFILE_PAGE = 6,
    EDIT_SPECIFIC_PROFILE_PAGE = 7,
    GRAPH_PAGE = 8,
    SELECT_ACTIVE_PROFILE_PAGE = 9,
    INSULIN_PAGE = 10,
    HISTORY_PAGE = 11
};
